services:
  karakterer-net-app:
    container_name: karakterer-net-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-./}:/app
      - /app/node_modules/
    ports:
      - "3000:3000"
    depends_on:
      - karakterer-net-db

  karakterer-net-db:
    container_name: karakterer-net-db
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: karakterer
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
