name: deploy

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn next build
        env:
          DATABASE_URL: ${{ secrets.REMOTE_DATABASE_URL }}

      - name: Copy static files
        run: |
          cp -r ./.next/static ./.next/standalone/.next/
          cp -r ./public ./.next/standalone/

      - name: Zip build
        run: |
          cd ./.next/standalone/
          zip release.zip . -r

      - name: Upload build
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          source: "./.next/standalone/release.zip"
          target: ${{ secrets.REMOTE_DIR }}
          strip_components: 4

      - name: Delete old build, unzip new build and restart server process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER }}
          username: ${{ secrets.REMOTE_USERNAME }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd ${{ secrets.REMOTE_DIR }}
            rm -rv !(".env"|"release.zip")
            rm -rv .next
            unzip release.zip
            rm release.zip
            systemctl restart karakterer-net.service
